/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as PortfolioIndexImport } from './routes/portfolio/index'
import { Route as ProfileEditImport } from './routes/profile/edit'
import { Route as ProfileAddPortfolioImport } from './routes/profile/add-portfolio'
import { Route as ProfileAddAwardImport } from './routes/profile/add-award'
import { Route as AuthSignUpImport } from './routes/auth/signUp'
import { Route as AuthSignInImport } from './routes/auth/signIn'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'

// Create Virtual Routes

const AwardIndexLazyImport = createFileRoute('/award/')()
const AboutIndexLazyImport = createFileRoute('/about/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AwardIndexLazyRoute = AwardIndexLazyImport.update({
  id: '/award/',
  path: '/award/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/award/index.lazy').then((d) => d.Route))

const AboutIndexLazyRoute = AboutIndexLazyImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about/index.lazy').then((d) => d.Route))

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIndexRoute = PortfolioIndexImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileEditRoute = ProfileEditImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRoute,
} as any)

const ProfileAddPortfolioRoute = ProfileAddPortfolioImport.update({
  id: '/profile/add-portfolio',
  path: '/profile/add-portfolio',
  getParentRoute: () => rootRoute,
} as any)

const ProfileAddAwardRoute = ProfileAddAwardImport.update({
  id: '/profile/add-award',
  path: '/profile/add-award',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/signUp',
  path: '/auth/signUp',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/signIn',
  path: '/auth/signIn',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/signIn': {
      id: '/auth/signIn'
      path: '/auth/signIn'
      fullPath: '/auth/signIn'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/signUp': {
      id: '/auth/signUp'
      path: '/auth/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/profile/add-award': {
      id: '/profile/add-award'
      path: '/profile/add-award'
      fullPath: '/profile/add-award'
      preLoaderRoute: typeof ProfileAddAwardImport
      parentRoute: typeof rootRoute
    }
    '/profile/add-portfolio': {
      id: '/profile/add-portfolio'
      path: '/profile/add-portfolio'
      fullPath: '/profile/add-portfolio'
      preLoaderRoute: typeof ProfileAddPortfolioImport
      parentRoute: typeof rootRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/award/': {
      id: '/award/'
      path: '/award'
      fullPath: '/award'
      preLoaderRoute: typeof AwardIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signIn': typeof AuthSignInRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/profile/add-award': typeof ProfileAddAwardRoute
  '/profile/add-portfolio': typeof ProfileAddPortfolioRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/about': typeof AboutIndexLazyRoute
  '/award': typeof AwardIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signIn': typeof AuthSignInRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/profile/add-award': typeof ProfileAddAwardRoute
  '/profile/add-portfolio': typeof ProfileAddPortfolioRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/about': typeof AboutIndexLazyRoute
  '/award': typeof AwardIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signIn': typeof AuthSignInRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/profile/add-award': typeof ProfileAddAwardRoute
  '/profile/add-portfolio': typeof ProfileAddPortfolioRoute
  '/profile/edit': typeof ProfileEditRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/about/': typeof AboutIndexLazyRoute
  '/award/': typeof AwardIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/profile/add-award'
    | '/profile/add-portfolio'
    | '/profile/edit'
    | '/portfolio'
    | '/profile'
    | '/about'
    | '/award'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/profile/add-award'
    | '/profile/add-portfolio'
    | '/profile/edit'
    | '/portfolio'
    | '/profile'
    | '/about'
    | '/award'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/profile/add-award'
    | '/profile/add-portfolio'
    | '/profile/edit'
    | '/portfolio/'
    | '/profile/'
    | '/about/'
    | '/award/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ProfileAddAwardRoute: typeof ProfileAddAwardRoute
  ProfileAddPortfolioRoute: typeof ProfileAddPortfolioRoute
  ProfileEditRoute: typeof ProfileEditRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  AboutIndexLazyRoute: typeof AboutIndexLazyRoute
  AwardIndexLazyRoute: typeof AwardIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ProfileAddAwardRoute: ProfileAddAwardRoute,
  ProfileAddPortfolioRoute: ProfileAddPortfolioRoute,
  ProfileEditRoute: ProfileEditRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  AboutIndexLazyRoute: AboutIndexLazyRoute,
  AwardIndexLazyRoute: AwardIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/forgot-password",
        "/auth/signIn",
        "/auth/signUp",
        "/profile/add-award",
        "/profile/add-portfolio",
        "/profile/edit",
        "/portfolio/",
        "/profile/",
        "/about/",
        "/award/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/signIn": {
      "filePath": "auth/signIn.tsx"
    },
    "/auth/signUp": {
      "filePath": "auth/signUp.tsx"
    },
    "/profile/add-award": {
      "filePath": "profile/add-award.tsx"
    },
    "/profile/add-portfolio": {
      "filePath": "profile/add-portfolio.tsx"
    },
    "/profile/edit": {
      "filePath": "profile/edit.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/about/": {
      "filePath": "about/index.lazy.tsx"
    },
    "/award/": {
      "filePath": "award/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
